//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellphoneService.Repository.DbStorage.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CellphoneServiceEntities : DbContext
    {
        public CellphoneServiceEntities()
            : base("name=CellphoneServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<Recharge> Recharge { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
