//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellphoneService.Repository.DbStorage.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public decimal Value { get; set; }
        public int Seconds { get; set; }
        public int BonusSeconds { get; set; }
        public string BonusDescription { get; set; }
        public int TotalSeconds { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
